=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/exchange/dtdForSchemaExchange.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT schemaExchange (source, target)>
<!ELEMENT source (relation+)>
<!ELEMENT target (relation+)>
<!ELEMENT relation (key+, attribute*, fkey*, function*)>
<!ELEMENT key EMPTY>
<!ELEMENT fkey (refRelName)>
<!ELEMENT refRelName (#PCDATA)>
<!ELEMENT attribute EMPTY>
<!ELEMENT function (attributeName)>
<!ELEMENT attributeName (#PCDATA)>
<!ATTLIST schemaExchange name CDATA #REQUIRED>
<!ATTLIST relation name CDATA #REQUIRED>
<!ATTLIST key name CDATA #REQUIRED>
<!ATTLIST fkey name CDATA #REQUIRED>
<!ATTLIST attribute name CDATA #REQUIRED>
<!ATTLIST function name CDATA #REQUIRED>
<!ATTLIST key constant CDATA #IMPLIED>
<!ATTLIST fkey constant CDATA #IMPLIED>
<!ATTLIST attribute constant CDATA #IMPLIED>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/scenario/t2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="t2 - copia relazioni perde fk">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<fkey name="fk1">
				<refRelName>r2</refRelName>
			</fkey>
		</relation>
		<relation name="r2">
			<key name="k2"/>
			<attribute name="a2"/>
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a3"/>
			<fkey name="fk2">
				<refRelName>r1</refRelName>
			</fkey>
		</relation>
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
		</relation>
		<relation name="r2">
			<key name="k2"/>
			<attribute name="a2"/>
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a3"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/scenario/t6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="t6 - denormalizzazione con costanti">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="title"/>
			<fkey name="fk1">
				<refRelName>r2</refRelName>
			</fkey>
		</relation>
		<relation name="r2">
			<key name="k2"/>
			<attribute name="a2" constant="name"/>
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a3" constant="office"/>
			<fkey name="fk2">
				<refRelName>r1</refRelName>
			</fkey>
		</relation>
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<attribute name="a2"/>
			<attribute name="a3"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/exchange/SEcourse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="denormalizzazione con costante">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="course"/>
			<attribute name="a2"/>
			<fkey name="fk1">
				<refRelName>r3</refRelName>
			</fkey>
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a3"/>
		</relation>
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<attribute name="a3"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/testPapotti/company10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="C10-company CMS esterno con diverse FK in source e target-bis">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="title"/>
			<attribute name="a2"/>
			<fkey name="fk2">
				<refRelName>r2</refRelName>
			</fkey>
		</relation>

		<relation name="r2">
			<key name="k2"/>
			<attribute name="a3" constant="file"/>
			<attribute name="a4"/>
		</relation>
		
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<fkey name="fk3">
				<refRelName>r3</refRelName>
			</fkey>
		</relation>
		
		<relation name="r3">
			<key name="k2"/>
			<attribute name="a3"/>
		</relation>
		
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/testPapotti/Uni7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="U7-copia e proiezione con 2+1 costanti">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="course"/>
			<attribute name="a2"/>
			<fkey name="fk1" constant="university">
				<refRelName>r3</refRelName>
			</fkey>
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a3" constant="address"/>
			<attribute name="a4"/>
		</relation>
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<fkey name="fk1">
				<refRelName>r3</refRelName>
			</fkey>
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a2"/>
			<attribute name="a3"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/testPapotti/company5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="C5-company CMS esterno title e file in tabella referenziata">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="title"/>
			<attribute name="a2"/>
			<fkey name="fk2">
				<refRelName>r2</refRelName>
			</fkey>
		</relation>

		<relation name="r2">
			<key name="k2"/>
			<attribute name="a3" constant="file"/>
			<attribute name="a4"/>
		</relation>
		
		
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<attribute name="a2"/>
			<attribute name="a3"/>
		</relation>
	</target>
</schemaExchange>
