=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/exchange/dtdForSchemaExchange.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT schemaExchange (source, target)>
<!ELEMENT source (relation+)>
<!ELEMENT target (relation+)>
<!ELEMENT relation (key+, attribute*, fkey*, function*)>
<!ELEMENT key EMPTY>
<!ELEMENT fkey (refRelName)>
<!ELEMENT refRelName (#PCDATA)>
<!ELEMENT attribute EMPTY>
<!ELEMENT function (attributeName)>
<!ELEMENT attributeName (#PCDATA)>
<!ATTLIST schemaExchange name CDATA #REQUIRED>
<!ATTLIST relation name CDATA #REQUIRED>
<!ATTLIST key name CDATA #REQUIRED>
<!ATTLIST fkey name CDATA #REQUIRED>
<!ATTLIST attribute name CDATA #REQUIRED>
<!ATTLIST function name CDATA #REQUIRED>
<!ATTLIST key constant CDATA #IMPLIED>
<!ATTLIST fkey constant CDATA #IMPLIED>
<!ATTLIST attribute constant CDATA #IMPLIED>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/testPapotti/Uni4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="U4-denormalizzazione con 1+2 costanti">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="course"/>
			<attribute name="a2"/>
			<fkey name="fk1">
				<refRelName>r3</refRelName>
			</fkey>
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a3" constant="name"/>
			<attribute name="a4" constant="rating"/>			
			<attribute name="a5"/>
		</relation>
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<attribute name="a4"/>
			<attribute name="a3"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/testPapotti/General4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="G-4copia semplice, generazione  attributo">
	<source>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a5"/>
		</relation>

	</source>
	<target>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a6"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/testPapotti/company1 (copy_mod).xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="C1-company CMS esterno con FK">
	<source>
		<relation name="r1"> 010200aa
			<key name="k1"/>
			<attribute name="a1" constant="title"/>
			<fkey name="fk1">
				<refRelName>r2</refRelName>
			</fkey>
			<fkey name="fk2">
				<refRelName>r3</refRelName>
			</fkey>
		</relation> 010001aa
		<relation name="r2">
			<key name="k2"/>
			<attribute name="a2" constant="officePhone" />
		</relation>
		<relation name="r3"> 010001aaa
			<key name="k3"/>
			<attribute name="a31" constant="file" />
			<attribute name="a32" />
		</relation>
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<attribute name="a2"/>
			<attribute name="a3"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/testPapotti/company4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="C4-company CMS esterno title e bonus">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="title"/>
			<attribute name="a2" constant="bonus"/>
		</relation>
		
		
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<attribute name="a2"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/testPapotti/company3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="C3-company CMS esterno solo title">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1" constant="title"/>
		</relation>
		
		
	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>

		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/testPapotti/General5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="G5-copia semplice, generazione relazione">
	<source>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a5"/>
		</relation>

	</source>
	<target>
		<relation name="r4">
			<key name="k3"/>
			<attribute name="a5"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/testPapotti/General7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="G7-copia semplice, generazione secondo attributo">
	<source>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a5"/>
		</relation>

	</source>
	<target>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a5"/>
			<attribute name="a6"/>
		</relation>
	</target>
</schemaExchange>

=== LucaLanziani/Ferret_on_DB/testPapotti/General1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schemaExchange SYSTEM "dtdForSchemaExchange.dtd">
<schemaExchange name="G1-denormalizzazione catena di join">
	<source>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<fkey name="fk1">
				<refRelName>r2</refRelName>
			</fkey>
		</relation>
		<relation name="r2">
			<key name="k2"/>
			<attribute name="a3"/>			
			<fkey name="fk2">
				<refRelName>r3</refRelName>
			</fkey>		
		</relation>
		<relation name="r3">
			<key name="k3"/>
			<attribute name="a5"/>
		</relation>

	</source>
	<target>
		<relation name="r1">
			<key name="k1"/>
			<attribute name="a1"/>
			<attribute name="a3"/>
			<attribute name="a5"/>
		</relation>
	</target>
</schemaExchange>
