=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/chase/dtdForChase.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataExchange (source, target)>
<!ELEMENT source (relation+)>
<!ELEMENT target (relation+)>
<!ELEMENT relation (key+, attribute*, fkey*, function*)>
<!ELEMENT key EMPTY>
<!ELEMENT fkey (refRelName)>
<!ELEMENT refRelName (#PCDATA)>
<!ELEMENT attribute EMPTY>
<!ELEMENT function (attributeName)>
<!ELEMENT attributeName (#PCDATA)>
<!ATTLIST dataExchange name CDATA #REQUIRED>
<!ATTLIST relation name CDATA #REQUIRED>
<!ATTLIST key name CDATA #REQUIRED>
<!ATTLIST fkey name CDATA #REQUIRED>
<!ATTLIST attribute name CDATA #REQUIRED>
<!ATTLIST function name CDATA #REQUIRED>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/chase/chase-simple-fk2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataExchange SYSTEM "dtdForChase.dtd">
<dataExchange name="recipe">
	<source>
		<relation name="DEPT">
			<key name="did"/>
			<attribute name="dname"/>
			<attribute name="floor"/>
			<attribute name="manager"/>
			<fkey name="building">
				<refRelName>BUILD</refRelName>
			</fkey>
		</relation>
		<relation name="BUILD">
			<key name="bid"/>
			<attribute name="bname"/>
		</relation>
	</source>
	<target>
		<relation name="DEPT">
			<key name="dname"/>
			<key name="floor"/>
			<key name="manager"/>
			<attribute name="bname"/>
			<fkey name="bid">
				<refRelName>BUILD</refRelName>
			</fkey>
		</relation>
		<relation name="BUILD">
			<key name="did"/>
			<attribute name="bname"/>
		</relation>
	</target>
</dataExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/chase/chase-1-n-fk.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataExchange SYSTEM "dtdForChase.dtd">
<dataExchange name="univ">
	<source>
		<relation name="STUD">
			<key name="sid"/>
			<attribute name="bname"/>
			<attribute name="studname"/>
			<attribute name="studsurname"/>
			<attribute name="floor"/>
			<attribute name="dname"/>
			<attribute name="studbirthday"/>
			<attribute name="manname"/>
		</relation>
	</source>
	<target>
		<relation name="R1">
			<key name="k2"/>
			<attribute name="dname"/>
			<attribute name="floor"/>
			<attribute name="bname"/>
			<attribute name="manname"/>
			<attribute name="studname"/>
			<attribute name="studsurname"/>
			<attribute name="studbirthday"/>
			<fkey name="fk4">
				<refRelName>R6</refRelName>
			</fkey>
			<fkey name="fk5">
				<refRelName>R9</refRelName>
			</fkey>
		</relation>
		<relation name="R6">
			<key name="k7"/>
			<attribute name="dname"/>
			<attribute name="floor"/>
			<attribute name="bname"/>
			<attribute name="manname"/>
			<attribute name="studname"/>
			<attribute name="studsurname"/>
			<attribute name="studbirthday"/>
		</relation>
		<relation name="R9">
			<key name="k10"/>
			<attribute name="dname"/>
			<attribute name="floor"/>
			<attribute name="bname"/>
			<attribute name="manname"/>
			<attribute name="studname"/>
			<attribute name="studsurname"/>
			<attribute name="studbirthday"/>
		</relation>
		<relation name="STUD">
			<key name="sid"/>
			<attribute name="dname"/>
			<attribute name="floor"/>
			<attribute name="bname"/>
			<attribute name="manname"/>
			<attribute name="studname"/>
			<attribute name="studsurname"/>
			<attribute name="studbirthday"/>
			<fkey name="fk15">
				<refRelName>R1</refRelName>
			</fkey>
		</relation>
	</target>
</dataExchange>

=== LucaLanziani/Ferret_on_DB/gaia-cbd-read-only/GAIA-CBD/src/xml/chase/chase-simple1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataExchange SYSTEM "dtdForChase.dtd">
<dataExchange name="recipe">
	<source>
		<relation name="DEPT">
			<key name="did"/>
			<attribute name="dname"/>
			<attribute name="floor"/>
			<attribute name="manager"/>
			<attribute name="building"/>
		</relation>
	</source>
	<target>
		<relation name="DEPT">
			<key name="dname"/>
			<key name="floor"/>
			<key name="manager"/>
			<key name="building"/>
			<attribute name="did"/>
		</relation>
	</target>
</dataExchange>
